CREATE TABLE IF NOT EXISTS accounts (
id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
name varchar(255) COMMENT 'User Name',
email varchar(255) COMMENT 'User Email',
picture varchar(255) COMMENT 'User Picture'
) default charset utf8 COMMENT '';

CREATE TABLE IF NOT EXISTS keeps (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
creatorId VARCHAR(255) NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(500),
img VARCHAR(2000) NOT NULL,
comments VARCHAR(500),
views INT NOT NULL DEFAULT 0,
kept INT NOT NULL DEFAULT 0,
FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
) default charset utf8 COMMENT '';

CREATE TABLE IF NOT EXISTS vaultKeeps (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
creatorId VARCHAR(255) NOT NULL,
vaultId INT NOT NULL,
keepId INT NOT NULL
) default charset utf8 COMMENT '';

CREATE TABLE IF NOT EXISTS vaults (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
creatorId VARCHAR(255) NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(500),
img VARCHAR(2000) NOT NULL,
isPrivate BOOLEAN NOT NULL DEFAULT FALSE,
FOREIGN KEY (creatorId) REFERENCES accounts (id) ON DELETE CASCADE
) default charset utf8 COMMENT '';